### ISSUE TITLE
Admin from one company can see all meetings for other companies

### ISSUE THREAD

**Issue by mlgiardina** [tiy-austin-ror-may2015/crs2000#111]
On the meetings_report part of the admin dashboard, I can see all the meetings from other companies.

**Comment by mlgiardina** [comment]
@JMD1986 were you working on this?

**Comment by JMD1986** [comment]
OH NO! I hadn't done any of the admin scope stuff, only regular views. I'll get on that right now.

**Comment by JMD1986** [comment]
fixed i think
